# Generated by Django 4.1.2 on 2022-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jumlah_terjual', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
        ),
    ]
