# Generated by Django 4.1.2 on 2022-10-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='nama_umkm',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
