# Generated by Django 4.1.2 on 2022-11-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('penjualan', '0002_laporan_nama_umkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='nama_umkm',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='landing.profile'),
        ),
    ]
