# Generated by Django 4.1.2 on 2022-11-02 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('penjualan', '0003_alter_laporan_nama_umkm'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nama_umkm',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
