# Generated by Django 4.1 on 2022-10-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileUMKM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255, verbose_name="Nama UMKM")),
                (
                    "no_telepon",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("kontak", models.CharField(max_length=32)),
                ("kota", models.CharField(max_length=32)),
                ("provinsi", models.CharField(max_length=32)),
                ("kodepos", models.PositiveIntegerField(verbose_name="Kode Pos")),
                ("foto", models.URLField(blank=True)),
                (
                    "tanggal_pembuatan",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Pembuatan"
                    ),
                ),
                (
                    "pemilik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lokasi_UMKM",
                        to="landing.profile",
                    ),
                ),
            ],
        ),
    ]
