# Generated by Django 4.1 on 2022-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileUMKM", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileumkm",
            name="foto",
            field=models.URLField(
                blank=True,
                default="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
            ),
        ),
        migrations.AlterField(
            model_name="profileumkm",
            name="tanggal_pembuatan",
            field=models.DateField(auto_now_add=True, verbose_name="Tanggal Pembuatan"),
        ),
    ]
