# Generated by Django 4.1 on 2022-10-27 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('berita', '0002_rename_news_newsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentModel',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='title',
            new_name='news_title',
        ),
    ]
