# Generated by Django 4.1 on 2022-10-28 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_commentmodel_comments_substance_newsmodel_news_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='berita.newsmodel'),
        ),
    ]
