# Generated by Django 4.1 on 2022-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_commentmodel_date_added_alter_commentmodel_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
