# Generated by Django 4.1 on 2022-10-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0006_alter_commentmodel_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
