# Generated by Django 4.1 on 2022-10-28 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0007_alter_commentmodel_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='news_image',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
