# Generated by Django 4.1 on 2022-10-29 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0008_newsmodel_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='news_published',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
