# Generated by Django 4.1 on 2022-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0009_newsmodel_news_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_source',
            field=models.URLField(max_length=500),
        ),
    ]
