# Generated by Django 4.1 on 2022-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0012_alter_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
