# Generated by Django 4.1 on 2022-11-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("berita", "0013_alter_commentmodel_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="berita.newsmodel"
            ),
        ),
    ]
